name: google_place
description: A new Flutter package for handle google place api that place search and details and photos and autocomplete and query autocomplete requests are available
version: 0.3.3
homepage: https://github.com/bazrafkan/google_place

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
